name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This is a stale issue. It has not been updated for a long time.'
        stale-pr-message: 'This is a stale pull request. It has not been updated for a long time.'
        stale-issue-label: 'Follow-up: Stale issue'
        stale-pr-label: 'Follow-up: Stale pull request'
